In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
low_memory = False

In [2]:
motive_data = pd.read_csv("19_Motive.csv",encoding = "ISO-8859-1")
victim_data = pd.read_csv("32_Victim.csv",encoding = "ISO-8859-1")
firearms_data = pd.read_csv("34_Firearm.csv",encoding = "ISO-8859-1")
air_data = pd.read_csv("data.csv",encoding = "ISO-8859-1")

C:\Users\RF18\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [8]:
df_motive_data = pd.DataFrame(motive_data)
#df_motive_data = df_motive_data.set_index('Area_Name')
df_motive_data.head()

,Area_Name,Year,CHNAMurder_Cause_By_TerroristExtremist,CHNAMurder_Cause_Casteism,CHNAMurder_Cause_Class_Conflict,CHNAMurder_Cause_Communalism,CHNAMurder_Cause_Dowry,CHNAMurder_Cause_For_Political_reason,CHNAMurder_Cause_Gain,CHNAMurder_Cause_Love_AffairsSexual_Relations,...,Murder_Cause_Dowry,Murder_Cause_For_Political_reason,Murder_Cause_Gain,Murder_Cause_Love_AffairsSexual_Relations,Murder_Cause_Lunacy,Murder_Cause_Other_Causes_or_Motives,Murder_Cause_Personal_Vendetta_or_Enmity,Murder_Cause_Property_Dispute,Murder_Cause_Total,Murder_Cause_Witchcraft
0,Odisha,2007,0,11,0,0,2,0,0,0,...,138,4,60,61,1,755,113,43,1210,28
1,Jharkhand,2002,0,3,2,2,13,3,7,9,...,70,25,103,158,3,599,242,228,1488,26
2,Jharkhand,2004,0,3,2,2,13,3,7,9,...,70,25,103,158,3,599,242,228,1488,26
3,Bihar,2010,0,2,2,0,11,0,47,35,...,168,24,352,187,5,1228,441,916,3362,2
4,Karnataka,2002,0,1,0,0,0,0,0,1,...,52,6,55,130,0,1093,188,98,1627,0

In [9]:
df_motive_data.fillna(value=0, inplace=True)

In [10]:
df_motive_data

,Area_Name,Year,CHNAMurder_Cause_By_TerroristExtremist,CHNAMurder_Cause_Casteism,CHNAMurder_Cause_Class_Conflict,CHNAMurder_Cause_Communalism,CHNAMurder_Cause_Dowry,CHNAMurder_Cause_For_Political_reason,CHNAMurder_Cause_Gain,CHNAMurder_Cause_Love_AffairsSexual_Relations,...,Murder_Cause_Dowry,Murder_Cause_For_Political_reason,Murder_Cause_Gain,Murder_Cause_Love_AffairsSexual_Relations,Murder_Cause_Lunacy,Murder_Cause_Other_Causes_or_Motives,Murder_Cause_Personal_Vendetta_or_Enmity,Murder_Cause_Property_Dispute,Murder_Cause_Total,Murder_Cause_Witchcraft
0,Odisha,2007,0,11,0,0,2,0,0,0,...,138,4,60,61,1,755,113,43,1210,28
1,Jharkhand,2002,0,3,2,2,13,3,7,9,...,70,25,103,158,3,599,242,228,1488,26
2,Jharkhand,2004,0,3,2,2,13,3,7,9,...,70,25,103,158,3,599,242,228,1488,26
3,Bihar,2010,0,2,2,0,11,0,47,35,...,168,24,352,187,5,1228,441,916,3362,2
4,Karnataka,2002,0,1,0,0,0,0,0,1,...,52,6,55,130,0,1093,188,98,1627,0
5,Haryana,2006,0,1,1,0,1,0,3,1,...,19,2,50,74,0,319,192,181,873,34
6,Andaman & Nicobar Islands,2001,0,0,0,0,0,0,0,0,...,0,0,1,0,0,7,4,1,13,0
7,Andhra Pradesh,2001,0,0,1,0,0,0,1,2,...,96,39,122,355,7,1348,332,159,2602,20
8,Arunachal Pradesh,2001,0,0,0,0,0,0,0,1,...,0,0,8,5,0,48,16,2,83,0
9,Assam,2001,0,0,1,0,0,0,2,0,...,62,2,94,37,1,812,83,125,1356,3
10,Bihar,2001,0,0,1,0,12,0,15,6,...,288,47,310,178,4,1293,579,888,3643,1
11,Chandigarh,2001,0,0,0,0,0,0,0,0,...,0,0,0,0,0,11,2,2,15,0
12,Chhattisgarh,2001,0,0,0,0,1,0,1,2,...,21,0,25,75,21,456,129,81,880,14
13,Dadra & Nagar Haveli,2001,0,0,0,0,0,0,0,0,...,0,0,0,1,0,2,0,0,3,0
14,Daman & Diu,2001,0,0,0,0,0,0,0,0,...,0,0,1,1,0,4,0,1,7,0
15,Delhi,2001,0,0,0,0,0,0,1,0,...,20,0,36,67,3,307,56,56,547,0
16,Goa,2001,0,0,0,0,0,0,0,0,...,0,0,8,4,0,20,4,0,36,0
17,Gujarat,2001,0,0,0,0,0,0,77,0,...,24,0,89,152,14,681,133,127,1226,2
18,Haryana,2001,0,0,0,3,0,0,5,1,...,3,0,41,54,0,336,134,184,781,2
19,Himachal Pradesh,2001,0,0,0,0,0,0,0,0,...,1,0,4,11,0,72,15,16,119,0
20,Jammu & Kashmir,2001,6,0,0,0,0,0,0,0,...,1,0,0,4,0,69,18,23,1075,1
21,Jharkhand,2001,0,0,0,0,17,0,2,4,...,31,4,84,69,1,937,160,141,1507,21
22,Karnataka,2001,0,0,0,0,0,0,0,1,...,33,7,66,143,0,1142,140,91,1626,0
23,Kerala,2001,0,0,0,0,0,1,0,1,...,1,16,27,5,6,215,188,14,472,0
24,Lakshadweep,2001,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
25,Madhya Pradesh,2001,0,0,0,0,6,0,0,0,...,67,9,86,149,5,1407,440,240,2425,13
26,Maharashtra,2001,0,0,3,1,3,0,4,0,...,112,4,96,338,9,1837,228,150,2839,6
27,Manipur,2001,0,0,0,0,0,0,0,0,...,0,0,8,0,0,72,0,0,209,0
28,Meghalaya,2001,0,0,0,0,0,0,0,0,...,0,0,11,2,1,122,7,8,164,0
29,Mizoram,2001,0,0,0,0,0,0,0,0,...,0,0,3,3,0,16,9,0,31,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,Chandigarh,2010,0,0,0,0,0,0,0,0,...,0,0,0,2,0,16,3,0,21,0
321,Chhattisgarh,2010,0,0,0,1,1,0,0,1,...,19,0,26,72,2,661,66,66,1065,8
322,Dadra & Nagar Haveli,2010,0,0,0,0,0,0,0,0,...,0,0,0,1,0,5,0,0,6,0
323,Daman & Diu,2010,0,0,0,0,0,0,0,0,...,0,0,0,0,0,3,2,0,5,0
324,Delhi,2010,0,0,0,0,0,0,1,2,...,5,0,26,54,0,372,73,33,565,0
325,Goa,2010,0,0,0,0,0,0,0,0,...,0,0,3,2,0,20,10,0,35,0
326,Gujarat,2010,0,0,0,0,1,0,2,1,...,3,0,66,131,8,624,118,90,1048,5
327,Haryana,2010,0,0,1,0,0,0,2,2,...,17,0,40,42,1,390,215,241,1005,57
328,Himachal Pradesh,2010,0,0,0,0,0,0,0,0,...,0,0,3,10,0,102,5,12,132,0
329,Jammu & Kashmir,2010,0,0,0,0,0,0,0,0,...,2,0,1,8,0,100,9,20,217,0
330,Jharkhand,2010,0,0,0,0,0,0,0,7,...,36,9,154,105,1,916,146,259,1689,15
331,Karnataka,2010,0,0,0,0,0,0,0,1,...,67,8,71,99,0,1367,118,71,1805,1
332,Kerala,2010,0,0,0,0,0,0,0,0,...,0,6,25,5,2,212,103,10,363,0
333,Lakshadweep,2010,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
334,Madhya Pradesh,2010,0,0,0,1,0,0,1,1,...,44,19,81,175,3,1235,492,342,2423,18
335,Maharashtra,2010,2,0,0,0,0,0,0,1,...,116,4,69,236,6,1961,169,140,2744,11
336,Manipur,2010,0,0,0,0,0,0,0,0,...,0,0,0,0,0,63,0,0,92,0
337,Meghalaya,2010,0,0,0,0,0,0,0,0,...,0,3,23,2,0,67,19,11,134,2
338,Mizoram,2010,0,0,0,0,0,0,0,0,...,0,0,4,10,0,33,1,0,48,0
339,Nagaland,2010,0,0,0,0,0,0,0,0,...,0,0,0,0,0,43,0,0,45,0
340,Odisha,2010,0,0,0,0,0,0,0,0,...,309,2,48,66,0,650,140,51,1308,31
341,Puducherry,2010,0,0,0,0,0,0,0,0,...,1,0,0,5,0,5,20,2,33,0
342,Punjab,2010,0,0,0,0,0,0,4,2,...,6,0,8,137,0,622,63,71,907,0
343,Rajasthan,2010,0,0,0,0,4,0,0,0,...,39,0,28,45,0,1173,77,56,1421,2
344,Sikkim,2010,0,0,0,0,0,0,0,0,...,0,0,3,1,0,8,4,0,17,0
345,Tamil Nadu,2010,0,0,0,0,0,0,1,0,...,6,5,153,237,0,993,316,164,1875,0
346,Tripura,2010,0,0,0,0,2,0,0,2,...,14,0,20,13,0,13,57,32,150,0
347,Uttar Pradesh,2010,0,0,0,0,0,0,2,0,...,0,1,138,282,0,3597,220,161,4401,0
348,Uttarakhand,2010,0,0,0,0,0,0,0,1,...,0,0,7,13,0,151,0,5,176,0
349,West Bengal,2010,0,0,0,0,1,0,2,0,...,285,38,49,27,1,1665,145,43,2398,0

In [11]:
df_motive_data=df_motive_data.drop(['CHNAMurder_Cause_Total','Murder_Cause_Total'],1)
df_motive_data.head()

,Area_Name,Year,CHNAMurder_Cause_By_TerroristExtremist,CHNAMurder_Cause_Casteism,CHNAMurder_Cause_Class_Conflict,CHNAMurder_Cause_Communalism,CHNAMurder_Cause_Dowry,CHNAMurder_Cause_For_Political_reason,CHNAMurder_Cause_Gain,CHNAMurder_Cause_Love_AffairsSexual_Relations,...,Murder_Cause_Communalism,Murder_Cause_Dowry,Murder_Cause_For_Political_reason,Murder_Cause_Gain,Murder_Cause_Love_AffairsSexual_Relations,Murder_Cause_Lunacy,Murder_Cause_Other_Causes_or_Motives,Murder_Cause_Personal_Vendetta_or_Enmity,Murder_Cause_Property_Dispute,Murder_Cause_Witchcraft
0,Odisha,2007,0,11,0,0,2,0,0,0,...,0,138,4,60,61,1,755,113,43,28
1,Jharkhand,2002,0,3,2,2,13,3,7,9,...,0,70,25,103,158,3,599,242,228,26
2,Jharkhand,2004,0,3,2,2,13,3,7,9,...,0,70,25,103,158,3,599,242,228,26
3,Bihar,2010,0,2,2,0,11,0,47,35,...,0,168,24,352,187,5,1228,441,916,2
4,Karnataka,2002,0,1,0,0,0,0,0,1,...,4,52,6,55,130,0,1093,188,98,0

In [13]:
formatted_df = pd.melt(df_motive_data, id_vars=['Area_Name','Year'], value_vars=['CHNAMurder_Cause_By_TerroristExtremist',
'CHNAMurder_Cause_Casteism',
'CHNAMurder_Cause_Class_Conflict',
'CHNAMurder_Cause_Communalism',
'CHNAMurder_Cause_Dowry',
'CHNAMurder_Cause_For_Political_reason',
'CHNAMurder_Cause_Gain',
'CHNAMurder_Cause_Love_AffairsSexual_Relations',
'CHNAMurder_Cause_Lunacy',
'CHNAMurder_Cause_Other_Causes_or_Motives',
'CHNAMurder_Cause_Personal_Vendetta_or_Enmity',
'CHNAMurder_Cause_Property_Dispute',
'CHNAMurder_Cause_Witchcraft',
'Murder_Cause_By_TerroristExtremist',
'Murder_Cause_Casteism',
'Murder_Cause_Class_Conflict',
'Murder_Cause_Communalism',
'Murder_Cause_Dowry',
'Murder_Cause_For_Political_reason',
'Murder_Cause_Gain',
'Murder_Cause_Love_AffairsSexual_Relations',
'Murder_Cause_Lunacy',
'Murder_Cause_Other_Causes_or_Motives',
'Murder_Cause_Personal_Vendetta_or_Enmity',
'Murder_Cause_Property_Dispute',
'Murder_Cause_Witchcraft',
],var_name="type_of_motive",value_name="freq")
formatted_df = formatted_df.sort_values(by=['Area_Name'])
formatted_df = formatted_df.set_index('Area_Name')
formatted_df

,Year,type_of_motive,freq
Area_Name,,,
Andaman & Nicobar Islands,2010,CHNAMurder_Cause_By_TerroristExtremist,0
Andaman & Nicobar Islands,2008,CHNAMurder_Cause_Class_Conflict,0
Andaman & Nicobar Islands,2002,Murder_Cause_Class_Conflict,4
Andaman & Nicobar Islands,2006,Murder_Cause_By_TerroristExtremist,0
Andaman & Nicobar Islands,2007,CHNAMurder_Cause_Dowry,0
Andaman & Nicobar Islands,2008,CHNAMurder_Cause_Gain,0
Andaman & Nicobar Islands,2006,CHNAMurder_Cause_Communalism,0
Andaman & Nicobar Islands,2003,CHNAMurder_Cause_Personal_Vendetta_or_Enmity,0
Andaman & Nicobar Islands,2008,Murder_Cause_Witchcraft,0
Andaman & Nicobar Islands,2009,CHNAMurder_Cause_Love_AffairsSexual_Relations,0
Andaman & Nicobar Islands,2003,Murder_Cause_Lunacy,1
Andaman & Nicobar Islands,2002,CHNAMurder_Cause_Personal_Vendetta_or_Enmity,0
Andaman & Nicobar Islands,2006,CHNAMurder_Cause_Property_Dispute,0
Andaman & Nicobar Islands,2007,CHNAMurder_Cause_By_TerroristExtremist,0
Andaman & Nicobar Islands,2005,Murder_Cause_By_TerroristExtremist,0
Andaman & Nicobar Islands,2004,Murder_Cause_Dowry,1
Andaman & Nicobar Islands,2004,Murder_Cause_Personal_Vendetta_or_Enmity,5
Andaman & Nicobar Islands,2003,Murder_Cause_Class_Conflict,3
Andaman & Nicobar Islands,2009,Murder_Cause_Witchcraft,0
Andaman & Nicobar Islands,2001,Murder_Cause_Class_Conflict,0
Andaman & Nicobar Islands,2010,Murder_Cause_Love_AffairsSexual_Relations,1
Andaman & Nicobar Islands,2003,CHNAMurder_Cause_Class_Conflict,1
Andaman & Nicobar Islands,2001,CHNAMurder_Cause_Gain,0
Andaman & Nicobar Islands,2005,CHNAMurder_Cause_Lunacy,0
Andaman & Nicobar Islands,2007,Murder_Cause_Property_Dispute,0
Andaman & Nicobar Islands,2004,CHNAMurder_Cause_Personal_Vendetta_or_Enmity,0
Andaman & Nicobar Islands,2008,CHNAMurder_Cause_By_TerroristExtremist,0
Andaman & Nicobar Islands,2010,Murder_Cause_Gain,0
Andaman & Nicobar Islands,2004,Murder_Cause_Gain,0
Andaman & Nicobar Islands,2005,CHNAMurder_Cause_Property_Dispute,0
...,...,...,...
West Bengal,2007,Murder_Cause_For_Political_reason,20
West Bengal,2006,Murder_Cause_For_Political_reason,7
West Bengal,2005,Murder_Cause_For_Political_reason,8
West Bengal,2004,Murder_Cause_For_Political_reason,15
West Bengal,2003,Murder_Cause_For_Political_reason,22
West Bengal,2002,Murder_Cause_For_Political_reason,19
West Bengal,2001,Murder_Cause_For_Political_reason,21
West Bengal,2010,Murder_Cause_Dowry,285
West Bengal,2009,Murder_Cause_Dowry,223
West Bengal,2008,Murder_Cause_Dowry,167
West Bengal,2007,Murder_Cause_Dowry,163
West Bengal,2006,Murder_Cause_Dowry,53
West Bengal,2005,Murder_Cause_Dowry,32
West Bengal,2008,Murder_Cause_Class_Conflict,58
West Bengal,2004,Murder_Cause_Dowry,16
West Bengal,2002,Murder_Cause_Dowry,17
West Bengal,2001,Murder_Cause_Dowry,9
West Bengal,2010,Murder_Cause_Communalism,0
West Bengal,2009,Murder_Cause_Communalism,0
West Bengal,2008,Murder_Cause_Communalism,5
West Bengal,2007,Murder_Cause_Communalism,0
West Bengal,2006,Murder_Cause_Communalism,2
West Bengal,2005,Murder_Cause_Communalism,0
West Bengal,2004,Murder_Cause_Communalism,0
West Bengal,2003,Murder_Cause_Communalism,0
West Bengal,2002,Murder_Cause_Communalism,0
West Bengal,2001,Murder_Cause_Communalism,0
West Bengal,2010,Murder_Cause_Class_Conflict,0
West Bengal,2003,Murder_Cause_Dowry,14
West Bengal,2010,Murder_Cause_Witchcraft,0

In [17]:
formatted_df.to_csv("Type_of_Motive.csv")